#!/usr/bin/env python

import numpy


HIP_LENGTH = 11
THIGH_LENGTH = 54
KNEE_LENGTH = 72
THIGH_REST_ANGLE = 1.4663392033212757
KNEE_REST_ANGLE = -1.4485440219526171
BASE_BETA = 0.22670942831590035


def abc_to_C(a, b, c):
    return numpy.arccos((a * a + b * b - c * c) / (2 * a * b))


HIP_CYLINDER_MIN_LENGTH = 16.0
HIP_CYLINDER_TRAVEL = 8.0
HIP_MIDDLE_CYLINDER_ZERO = 20.314961
HIP_CYLINDER_ZERO = 19.80315
HIP_CYLINDER_MAX_LENGTH = HIP_CYLINDER_MIN_LENGTH + HIP_CYLINDER_TRAVEL

THIGH_CYLINDER_MIN_LENGTH = 24.0
THIGH_CYLINDER_TRAVEL = 14.0
THIGH_CYLINDER_ZERO = THIGH_CYLINDER_MIN_LENGTH
THIGH_CYLINDER_MAX_LENGTH = THIGH_CYLINDER_MIN_LENGTH + THIGH_CYLINDER_TRAVEL

KNEE_CYLINDER_MIN_LENGTH = 20.0
KNEE_CYLINDER_TRAVEL = 12.0
KNEE_CYLINDER_ZERO = KNEE_CYLINDER_MIN_LENGTH + KNEE_CYLINDER_TRAVEL
KNEE_CYLINDER_MAX_LENGTH = KNEE_CYLINDER_MIN_LENGTH + KNEE_CYLINDER_TRAVEL

HIP_A = 6.83905
HIP_MIDDLE_B = 19.62051
HIP_B = 19.16327
THIGH_A = 10.21631
THIGH_B = 33.43093
KNEE_A = 7.4386
KNEE_B = 25.6021

HIP_ZERO_ANGLE = abc_to_C(HIP_A, HIP_B, HIP_CYLINDER_ZERO)
HIP_MIDDLE_ZERO_ANGLE = abc_to_C(HIP_A, HIP_MIDDLE_B, HIP_MIDDLE_CYLINDER_ZERO)
THIGH_ZERO_ANGLE = abc_to_C(THIGH_A, THIGH_B, THIGH_CYLINDER_ZERO)
KNEE_ZERO_ANGLE = abc_to_C(KNEE_A, KNEE_B, KNEE_CYLINDER_ZERO)

hip_angle = lambda c: abc_to_C(HIP_A, HIP_B, c) - HIP_ZERO_ANGLE
hip_middle_angle = lambda c: (
    abc_to_C(HIP_A, HIP_MIDDLE_B, c) - HIP_MIDDLE_ZERO_ANGLE)
thigh_angle = lambda c: abc_to_C(THIGH_A, THIGH_B, c) - THIGH_ZERO_ANGLE
knee_angle = lambda c: abc_to_C(KNEE_A, KNEE_B, c) - KNEE_ZERO_ANGLE

HIP_MIN_ANGLE = max(
    hip_angle(HIP_CYLINDER_MIN_LENGTH),
    -hip_angle(HIP_CYLINDER_MAX_LENGTH))
HIP_MAX_ANGLE = -HIP_MIN_ANGLE
HIP_MIDDLE_MIN_ANGLE = max(
    hip_middle_angle(HIP_CYLINDER_MIN_LENGTH),
    -hip_middle_angle(HIP_CYLINDER_MAX_LENGTH))
HIP_MIDDLE_MAX_ANGLE = -HIP_MIDDLE_MIN_ANGLE
THIGH_MIN_ANGLE = thigh_angle(THIGH_CYLINDER_MIN_LENGTH)
THIGH_MAX_ANGLE = thigh_angle(THIGH_CYLINDER_MAX_LENGTH)
KNEE_MIN_ANGLE = knee_angle(KNEE_CYLINDER_MIN_LENGTH)
KNEE_MAX_ANGLE = knee_angle(KNEE_CYLINDER_MAX_LENGTH)
