# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stompy.ui'
#
# Created: Thu Feb 22 20:20:59 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(756, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.estopCheck = QtGui.QCheckBox(self.centralwidget)
        self.estopCheck.setObjectName(_fromUtf8("estopCheck"))
        self.verticalLayout.addWidget(self.estopCheck)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.legTab = QtGui.QWidget()
        self.legTab.setObjectName(_fromUtf8("legTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.legTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.legGLWidget = GLViewWidget(self.legTab)
        self.legGLWidget.setMinimumSize(QtCore.QSize(400, 400))
        self.legGLWidget.setObjectName(_fromUtf8("legGLWidget"))
        self.gridLayout.addWidget(self.legGLWidget, 0, 1, 2, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.graphicsView_3 = PlotWidget(self.legTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_3.sizePolicy().hasHeightForWidth())
        self.graphicsView_3.setSizePolicy(sizePolicy)
        self.graphicsView_3.setMinimumSize(QtCore.QSize(200, 200))
        self.graphicsView_3.setBaseSize(QtCore.QSize(200, 200))
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        self.verticalLayout_9.addWidget(self.graphicsView_3)
        self.gridLayout.addLayout(self.verticalLayout_9, 1, 2, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.graphicsView_5 = PlotWidget(self.legTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_5.sizePolicy().hasHeightForWidth())
        self.graphicsView_5.setSizePolicy(sizePolicy)
        self.graphicsView_5.setMinimumSize(QtCore.QSize(200, 200))
        self.graphicsView_5.setBaseSize(QtCore.QSize(200, 200))
        self.graphicsView_5.setObjectName(_fromUtf8("graphicsView_5"))
        self.verticalLayout_8.addWidget(self.graphicsView_5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.legTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.hipADCProgress = QtGui.QProgressBar(self.legTab)
        self.hipADCProgress.setMaximum(65535)
        self.hipADCProgress.setProperty("value", 6500)
        self.hipADCProgress.setObjectName(_fromUtf8("hipADCProgress"))
        self.horizontalLayout_3.addWidget(self.hipADCProgress)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.legTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.thighADCProgress = QtGui.QProgressBar(self.legTab)
        self.thighADCProgress.setMaximum(65535)
        self.thighADCProgress.setProperty("value", 6500)
        self.thighADCProgress.setObjectName(_fromUtf8("thighADCProgress"))
        self.horizontalLayout_4.addWidget(self.thighADCProgress)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.legTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.kneeADCProgress = QtGui.QProgressBar(self.legTab)
        self.kneeADCProgress.setMaximum(65535)
        self.kneeADCProgress.setProperty("value", 6500)
        self.kneeADCProgress.setObjectName(_fromUtf8("kneeADCProgress"))
        self.horizontalLayout_5.addWidget(self.kneeADCProgress)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.legTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.calfADCProgress = QtGui.QProgressBar(self.legTab)
        self.calfADCProgress.setMaximum(65535)
        self.calfADCProgress.setProperty("value", 6500)
        self.calfADCProgress.setObjectName(_fromUtf8("calfADCProgress"))
        self.horizontalLayout_6.addWidget(self.calfADCProgress)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.tabs.addTab(self.legTab, _fromUtf8(""))
        self.PIDTab = QtGui.QWidget()
        self.PIDTab.setObjectName(_fromUtf8("PIDTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.PIDTab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pidPlotWidget = PlotWidget(self.PIDTab)
        self.pidPlotWidget.setObjectName(_fromUtf8("pidPlotWidget"))
        self.verticalLayout_6.addWidget(self.pidPlotWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_29 = QtGui.QLabel(self.PIDTab)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_5.addWidget(self.label_29)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_30 = QtGui.QLabel(self.PIDTab)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_24.addWidget(self.label_30)
        self.pidPSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.pidPSpin.setObjectName(_fromUtf8("pidPSpin"))
        self.horizontalLayout_24.addWidget(self.pidPSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_31 = QtGui.QLabel(self.PIDTab)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_25.addWidget(self.label_31)
        self.pidISpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.pidISpin.setObjectName(_fromUtf8("pidISpin"))
        self.horizontalLayout_25.addWidget(self.pidISpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_32 = QtGui.QLabel(self.PIDTab)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_26.addWidget(self.label_32)
        self.pidDSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.pidDSpin.setObjectName(_fromUtf8("pidDSpin"))
        self.horizontalLayout_26.addWidget(self.pidDSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_25 = QtGui.QLabel(self.PIDTab)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_4.addWidget(self.label_25)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_26 = QtGui.QLabel(self.PIDTab)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_21.addWidget(self.label_26)
        self.extendMinSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.extendMinSpin.setObjectName(_fromUtf8("extendMinSpin"))
        self.horizontalLayout_21.addWidget(self.extendMinSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_27 = QtGui.QLabel(self.PIDTab)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_22.addWidget(self.label_27)
        self.extendMaxSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.extendMaxSpin.setObjectName(_fromUtf8("extendMaxSpin"))
        self.horizontalLayout_22.addWidget(self.extendMaxSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_28 = QtGui.QLabel(self.PIDTab)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_23.addWidget(self.label_28)
        self.retractMinSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.retractMinSpin.setObjectName(_fromUtf8("retractMinSpin"))
        self.horizontalLayout_23.addWidget(self.retractMinSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_33 = QtGui.QLabel(self.PIDTab)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_30.addWidget(self.label_33)
        self.retractMaxSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.retractMaxSpin.setObjectName(_fromUtf8("retractMaxSpin"))
        self.horizontalLayout_30.addWidget(self.retractMaxSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_12 = QtGui.QLabel(self.PIDTab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.PIDTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.adcLimitMin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.adcLimitMin.setObjectName(_fromUtf8("adcLimitMin"))
        self.horizontalLayout_11.addWidget(self.adcLimitMin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.PIDTab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.adcLimitMax = QtGui.QDoubleSpinBox(self.PIDTab)
        self.adcLimitMax.setObjectName(_fromUtf8("adcLimitMax"))
        self.horizontalLayout_10.addWidget(self.adcLimitMax)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.pidCommitButton = QtGui.QPushButton(self.PIDTab)
        self.pidCommitButton.setObjectName(_fromUtf8("pidCommitButton"))
        self.horizontalLayout_29.addWidget(self.pidCommitButton)
        self.pidJointCombo = QtGui.QComboBox(self.PIDTab)
        self.pidJointCombo.setObjectName(_fromUtf8("pidJointCombo"))
        self.horizontalLayout_29.addWidget(self.pidJointCombo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_29)
        self.tabs.addTab(self.PIDTab, _fromUtf8(""))
        self.bodyTab = QtGui.QWidget()
        self.bodyTab.setObjectName(_fromUtf8("bodyTab"))
        self.tabs.addTab(self.bodyTab, _fromUtf8(""))
        self.walkTab = QtGui.QWidget()
        self.walkTab.setObjectName(_fromUtf8("walkTab"))
        self.tabs.addTab(self.walkTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabs)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 756, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuLegs = QtGui.QMenu(self.menubar)
        self.menuLegs.setObjectName(_fromUtf8("menuLegs"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuLegs.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.estopCheck.setText(_translate("MainWindow", "CheckBox", None))
        self.label.setText(_translate("MainWindow", "Hip", None))
        self.hipADCProgress.setFormat(_translate("MainWindow", "%v", None))
        self.label_2.setText(_translate("MainWindow", "Thigh", None))
        self.thighADCProgress.setFormat(_translate("MainWindow", "%v", None))
        self.label_3.setText(_translate("MainWindow", "Knee", None))
        self.kneeADCProgress.setFormat(_translate("MainWindow", "%v", None))
        self.label_4.setText(_translate("MainWindow", "Calf", None))
        self.calfADCProgress.setFormat(_translate("MainWindow", "%v", None))
        self.tabs.setTabText(self.tabs.indexOf(self.legTab), _translate("MainWindow", "Leg", None))
        self.label_29.setText(_translate("MainWindow", "PID", None))
        self.label_30.setText(_translate("MainWindow", "P", None))
        self.label_31.setText(_translate("MainWindow", "I", None))
        self.label_32.setText(_translate("MainWindow", "D", None))
        self.label_25.setText(_translate("MainWindow", "PWM", None))
        self.label_26.setText(_translate("MainWindow", "Extend min", None))
        self.label_27.setText(_translate("MainWindow", "Extend max", None))
        self.label_28.setText(_translate("MainWindow", "Retract min", None))
        self.label_33.setText(_translate("MainWindow", "Retract max", None))
        self.label_12.setText(_translate("MainWindow", "ADC limits", None))
        self.label_11.setText(_translate("MainWindow", "Min", None))
        self.label_10.setText(_translate("MainWindow", "Max", None))
        self.pidCommitButton.setText(_translate("MainWindow", "Commit", None))
        self.tabs.setTabText(self.tabs.indexOf(self.PIDTab), _translate("MainWindow", "PID", None))
        self.tabs.setTabText(self.tabs.indexOf(self.bodyTab), _translate("MainWindow", "Body", None))
        self.tabs.setTabText(self.tabs.indexOf(self.walkTab), _translate("MainWindow", "Walk", None))
        self.menuLegs.setTitle(_translate("MainWindow", "Legs", None))

from pyqtgraph.opengl import GLViewWidget
from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

