# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stompy.ui'
#
# Created: Sun Mar 17 14:06:38 2019
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setTabPosition(QtGui.QTabWidget.East)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.legTab = QtGui.QWidget()
        self.legTab.setObjectName(_fromUtf8("legTab"))
        self.legDisplay = LegDisplay(self.legTab)
        self.legDisplay.setGeometry(QtCore.QRect(10, 10, 400, 400))
        self.legDisplay.setMinimumSize(QtCore.QSize(0, 0))
        self.legDisplay.setObjectName(_fromUtf8("legDisplay"))
        self.layoutWidget = QtGui.QWidget(self.legTab)
        self.layoutWidget.setGeometry(QtCore.QRect(580, 170, 126, 27))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.hipADCProgress = QtGui.QProgressBar(self.layoutWidget)
        self.hipADCProgress.setMaximum(65535)
        self.hipADCProgress.setProperty("value", 6500)
        self.hipADCProgress.setObjectName(_fromUtf8("hipADCProgress"))
        self.horizontalLayout_3.addWidget(self.hipADCProgress)
        self.layoutWidget1 = QtGui.QWidget(self.legTab)
        self.layoutWidget1.setGeometry(QtCore.QRect(570, 200, 142, 27))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.thighADCProgress = QtGui.QProgressBar(self.layoutWidget1)
        self.thighADCProgress.setMaximum(65535)
        self.thighADCProgress.setProperty("value", 6500)
        self.thighADCProgress.setObjectName(_fromUtf8("thighADCProgress"))
        self.horizontalLayout_4.addWidget(self.thighADCProgress)
        self.layoutWidget2 = QtGui.QWidget(self.legTab)
        self.layoutWidget2.setGeometry(QtCore.QRect(570, 230, 138, 27))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.layoutWidget2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.kneeADCProgress = QtGui.QProgressBar(self.layoutWidget2)
        self.kneeADCProgress.setMaximum(65535)
        self.kneeADCProgress.setProperty("value", 6500)
        self.kneeADCProgress.setObjectName(_fromUtf8("kneeADCProgress"))
        self.horizontalLayout_5.addWidget(self.kneeADCProgress)
        self.layoutWidget3 = QtGui.QWidget(self.legTab)
        self.layoutWidget3.setGeometry(QtCore.QRect(570, 10, 148, 29))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_71 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_71.setMargin(0)
        self.horizontalLayout_71.setObjectName(_fromUtf8("horizontalLayout_71"))
        self.label_70 = QtGui.QLabel(self.layoutWidget3)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_71.addWidget(self.label_70)
        self.legXLineEdit = QtGui.QLineEdit(self.layoutWidget3)
        self.legXLineEdit.setObjectName(_fromUtf8("legXLineEdit"))
        self.horizontalLayout_71.addWidget(self.legXLineEdit)
        self.layoutWidget4 = QtGui.QWidget(self.legTab)
        self.layoutWidget4.setGeometry(QtCore.QRect(570, 40, 147, 29))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_70 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_70.setMargin(0)
        self.horizontalLayout_70.setObjectName(_fromUtf8("horizontalLayout_70"))
        self.label_69 = QtGui.QLabel(self.layoutWidget4)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_70.addWidget(self.label_69)
        self.legYLineEdit = QtGui.QLineEdit(self.layoutWidget4)
        self.legYLineEdit.setObjectName(_fromUtf8("legYLineEdit"))
        self.horizontalLayout_70.addWidget(self.legYLineEdit)
        self.layoutWidget5 = QtGui.QWidget(self.legTab)
        self.layoutWidget5.setGeometry(QtCore.QRect(570, 70, 147, 29))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_5 = QtGui.QLabel(self.layoutWidget5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_9.addWidget(self.label_5)
        self.legZLineEdit = QtGui.QLineEdit(self.layoutWidget5)
        self.legZLineEdit.setObjectName(_fromUtf8("legZLineEdit"))
        self.horizontalLayout_9.addWidget(self.legZLineEdit)
        self.layoutWidget6 = QtGui.QWidget(self.legTab)
        self.layoutWidget6.setGeometry(QtCore.QRect(570, 130, 146, 29))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_72 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_72.setMargin(0)
        self.horizontalLayout_72.setObjectName(_fromUtf8("horizontalLayout_72"))
        self.label_71 = QtGui.QLabel(self.layoutWidget6)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.horizontalLayout_72.addWidget(self.label_71)
        self.legLLineEdit = QtGui.QLineEdit(self.layoutWidget6)
        self.legLLineEdit.setObjectName(_fromUtf8("legLLineEdit"))
        self.horizontalLayout_72.addWidget(self.legLLineEdit)
        self.layoutWidget7 = QtGui.QWidget(self.legTab)
        self.layoutWidget7.setGeometry(QtCore.QRect(570, 100, 148, 29))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.horizontalLayout_69 = QtGui.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_69.setMargin(0)
        self.horizontalLayout_69.setObjectName(_fromUtf8("horizontalLayout_69"))
        self.label_68 = QtGui.QLabel(self.layoutWidget7)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_69.addWidget(self.label_68)
        self.legRLineEdit = QtGui.QLineEdit(self.layoutWidget7)
        self.legRLineEdit.setObjectName(_fromUtf8("legRLineEdit"))
        self.horizontalLayout_69.addWidget(self.legRLineEdit)
        self.layoutWidget8 = QtGui.QWidget(self.legTab)
        self.layoutWidget8.setGeometry(QtCore.QRect(570, 260, 131, 27))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.layoutWidget8)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        self.calfADCProgress = QtGui.QProgressBar(self.layoutWidget8)
        self.calfADCProgress.setMaximum(65535)
        self.calfADCProgress.setProperty("value", 6500)
        self.calfADCProgress.setObjectName(_fromUtf8("calfADCProgress"))
        self.horizontalLayout_6.addWidget(self.calfADCProgress)
        self.tabs.addTab(self.legTab, _fromUtf8(""))
        self.PIDTab = QtGui.QWidget()
        self.PIDTab.setObjectName(_fromUtf8("PIDTab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.PIDTab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pidLineChart = LineChart(self.PIDTab)
        self.pidLineChart.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pidLineChart.sizePolicy().hasHeightForWidth())
        self.pidLineChart.setSizePolicy(sizePolicy)
        self.pidLineChart.setObjectName(_fromUtf8("pidLineChart"))
        self.verticalLayout_6.addWidget(self.pidLineChart)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_29 = QtGui.QLabel(self.PIDTab)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_5.addWidget(self.label_29)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_30 = QtGui.QLabel(self.PIDTab)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_24.addWidget(self.label_30)
        self.pidPSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.pidPSpin.setDecimals(4)
        self.pidPSpin.setSingleStep(0.1)
        self.pidPSpin.setObjectName(_fromUtf8("pidPSpin"))
        self.horizontalLayout_24.addWidget(self.pidPSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_31 = QtGui.QLabel(self.PIDTab)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_25.addWidget(self.label_31)
        self.pidISpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.pidISpin.setDecimals(4)
        self.pidISpin.setSingleStep(0.1)
        self.pidISpin.setObjectName(_fromUtf8("pidISpin"))
        self.horizontalLayout_25.addWidget(self.pidISpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_32 = QtGui.QLabel(self.PIDTab)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_26.addWidget(self.label_32)
        self.pidDSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.pidDSpin.setDecimals(4)
        self.pidDSpin.setSingleStep(0.1)
        self.pidDSpin.setObjectName(_fromUtf8("pidDSpin"))
        self.horizontalLayout_26.addWidget(self.pidDSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_75 = QtGui.QHBoxLayout()
        self.horizontalLayout_75.setObjectName(_fromUtf8("horizontalLayout_75"))
        self.label_73 = QtGui.QLabel(self.PIDTab)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.horizontalLayout_75.addWidget(self.label_73)
        self.pidMinSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.pidMinSpin.setDecimals(2)
        self.pidMinSpin.setMinimum(-8192.0)
        self.pidMinSpin.setMaximum(8192.0)
        self.pidMinSpin.setSingleStep(1.0)
        self.pidMinSpin.setObjectName(_fromUtf8("pidMinSpin"))
        self.horizontalLayout_75.addWidget(self.pidMinSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_74 = QtGui.QHBoxLayout()
        self.horizontalLayout_74.setObjectName(_fromUtf8("horizontalLayout_74"))
        self.label_72 = QtGui.QLabel(self.PIDTab)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_74.addWidget(self.label_72)
        self.pidMaxSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.pidMaxSpin.setDecimals(2)
        self.pidMaxSpin.setMinimum(-8192.0)
        self.pidMaxSpin.setMaximum(8192.0)
        self.pidMaxSpin.setSingleStep(1.0)
        self.pidMaxSpin.setObjectName(_fromUtf8("pidMaxSpin"))
        self.horizontalLayout_74.addWidget(self.pidMaxSpin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_74)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.line = QtGui.QFrame(self.PIDTab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_25 = QtGui.QLabel(self.PIDTab)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_4.addWidget(self.label_25)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_26 = QtGui.QLabel(self.PIDTab)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_21.addWidget(self.label_26)
        self.extendMinSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.extendMinSpin.setDecimals(0)
        self.extendMinSpin.setMaximum(8192.0)
        self.extendMinSpin.setObjectName(_fromUtf8("extendMinSpin"))
        self.horizontalLayout_21.addWidget(self.extendMinSpin)
        self.extendMaxSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.extendMaxSpin.setDecimals(0)
        self.extendMaxSpin.setMaximum(8192.0)
        self.extendMaxSpin.setObjectName(_fromUtf8("extendMaxSpin"))
        self.horizontalLayout_21.addWidget(self.extendMaxSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_28 = QtGui.QLabel(self.PIDTab)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_23.addWidget(self.label_28)
        self.retractMinSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.retractMinSpin.setDecimals(0)
        self.retractMinSpin.setMaximum(8192.0)
        self.retractMinSpin.setObjectName(_fromUtf8("retractMinSpin"))
        self.horizontalLayout_23.addWidget(self.retractMinSpin)
        self.retractMaxSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.retractMaxSpin.setDecimals(0)
        self.retractMaxSpin.setMaximum(8192.0)
        self.retractMaxSpin.setObjectName(_fromUtf8("retractMaxSpin"))
        self.horizontalLayout_23.addWidget(self.retractMaxSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.label_27 = QtGui.QLabel(self.PIDTab)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_4.addWidget(self.label_27)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_33 = QtGui.QLabel(self.PIDTab)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_27.addWidget(self.label_33)
        self.seedFutureSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.seedFutureSpin.setDecimals(0)
        self.seedFutureSpin.setMaximum(8192.0)
        self.seedFutureSpin.setObjectName(_fromUtf8("seedFutureSpin"))
        self.horizontalLayout_27.addWidget(self.seedFutureSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_34 = QtGui.QLabel(self.PIDTab)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_28.addWidget(self.label_34)
        self.pidErrorThresholdSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.pidErrorThresholdSpin.setDecimals(0)
        self.pidErrorThresholdSpin.setMaximum(65535.0)
        self.pidErrorThresholdSpin.setSingleStep(1.0)
        self.pidErrorThresholdSpin.setObjectName(_fromUtf8("pidErrorThresholdSpin"))
        self.horizontalLayout_28.addWidget(self.pidErrorThresholdSpin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_28)
        spacerItem1 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line_2 = QtGui.QFrame(self.PIDTab)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_12 = QtGui.QLabel(self.PIDTab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_11 = QtGui.QLabel(self.PIDTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_11.addWidget(self.label_11)
        self.adcLimitMinSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.adcLimitMinSpin.setDecimals(0)
        self.adcLimitMinSpin.setMaximum(65535.0)
        self.adcLimitMinSpin.setObjectName(_fromUtf8("adcLimitMinSpin"))
        self.horizontalLayout_11.addWidget(self.adcLimitMinSpin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_10 = QtGui.QLabel(self.PIDTab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_10.addWidget(self.label_10)
        self.adcLimitMaxSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.adcLimitMaxSpin.setDecimals(0)
        self.adcLimitMaxSpin.setMaximum(65535.0)
        self.adcLimitMaxSpin.setObjectName(_fromUtf8("adcLimitMaxSpin"))
        self.horizontalLayout_10.addWidget(self.adcLimitMaxSpin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.label_13 = QtGui.QLabel(self.PIDTab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_14 = QtGui.QLabel(self.PIDTab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_12.addWidget(self.label_14)
        self.ditherTimeSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.ditherTimeSpin.setDecimals(0)
        self.ditherTimeSpin.setMaximum(1000000.0)
        self.ditherTimeSpin.setObjectName(_fromUtf8("ditherTimeSpin"))
        self.horizontalLayout_12.addWidget(self.ditherTimeSpin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_15 = QtGui.QLabel(self.PIDTab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_13.addWidget(self.label_15)
        self.ditherAmpSpin = QtGui.QDoubleSpinBox(self.PIDTab)
        self.ditherAmpSpin.setDecimals(0)
        self.ditherAmpSpin.setMaximum(8192.0)
        self.ditherAmpSpin.setObjectName(_fromUtf8("ditherAmpSpin"))
        self.horizontalLayout_13.addWidget(self.ditherAmpSpin)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.pidCommitButton = QtGui.QPushButton(self.PIDTab)
        self.pidCommitButton.setObjectName(_fromUtf8("pidCommitButton"))
        self.horizontalLayout_29.addWidget(self.pidCommitButton)
        self.pidJointCombo = QtGui.QComboBox(self.PIDTab)
        self.pidJointCombo.setObjectName(_fromUtf8("pidJointCombo"))
        self.pidJointCombo.addItem(_fromUtf8(""))
        self.pidJointCombo.addItem(_fromUtf8(""))
        self.pidJointCombo.addItem(_fromUtf8(""))
        self.horizontalLayout_29.addWidget(self.pidJointCombo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_29)
        self.tabs.addTab(self.PIDTab, _fromUtf8(""))
        self.bodyTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyTab.sizePolicy().hasHeightForWidth())
        self.bodyTab.setSizePolicy(sizePolicy)
        self.bodyTab.setObjectName(_fromUtf8("bodyTab"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.bodyTab)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.splitter = QtGui.QSplitter(self.bodyTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.bodyDisplay = BodyDisplay(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bodyDisplay.sizePolicy().hasHeightForWidth())
        self.bodyDisplay.setSizePolicy(sizePolicy)
        self.bodyDisplay.setMinimumSize(QtCore.QSize(0, 0))
        self.bodyDisplay.setObjectName(_fromUtf8("bodyDisplay"))
        self.horizontalLayout_14.addWidget(self.splitter)
        self.tabs.addTab(self.bodyTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabs)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.estopLabel = QtGui.QLabel(self.centralwidget)
        self.estopLabel.setObjectName(_fromUtf8("estopLabel"))
        self.horizontalLayout_8.addWidget(self.estopLabel)
        self.heightLabel = QtGui.QLabel(self.centralwidget)
        self.heightLabel.setObjectName(_fromUtf8("heightLabel"))
        self.horizontalLayout_8.addWidget(self.heightLabel)
        self.pressureLabel = QtGui.QLabel(self.centralwidget)
        self.pressureLabel.setObjectName(_fromUtf8("pressureLabel"))
        self.horizontalLayout_8.addWidget(self.pressureLabel)
        self.rpmLabel = QtGui.QLabel(self.centralwidget)
        self.rpmLabel.setObjectName(_fromUtf8("rpmLabel"))
        self.horizontalLayout_8.addWidget(self.rpmLabel)
        self.oilTempLabel = QtGui.QLabel(self.centralwidget)
        self.oilTempLabel.setObjectName(_fromUtf8("oilTempLabel"))
        self.horizontalLayout_8.addWidget(self.oilTempLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.legsMenu = QtGui.QMenu(self.menubar)
        self.legsMenu.setObjectName(_fromUtf8("legsMenu"))
        self.modesMenu = QtGui.QMenu(self.menubar)
        self.modesMenu.setObjectName(_fromUtf8("modesMenu"))
        self.calibrationMenu = QtGui.QMenu(self.menubar)
        self.calibrationMenu.setObjectName(_fromUtf8("calibrationMenu"))
        self.configurationMenu = QtGui.QMenu(self.menubar)
        self.configurationMenu.setObjectName(_fromUtf8("configurationMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.legsMenu.menuAction())
        self.menubar.addAction(self.modesMenu.menuAction())
        self.menubar.addAction(self.calibrationMenu.menuAction())
        self.menubar.addAction(self.configurationMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Hip", None))
        self.hipADCProgress.setFormat(_translate("MainWindow", "%v", None))
        self.label_2.setText(_translate("MainWindow", "Thigh", None))
        self.thighADCProgress.setFormat(_translate("MainWindow", "%v", None))
        self.label_3.setText(_translate("MainWindow", "Knee", None))
        self.kneeADCProgress.setFormat(_translate("MainWindow", "%v", None))
        self.label_70.setText(_translate("MainWindow", "X", None))
        self.label_69.setText(_translate("MainWindow", "Y", None))
        self.label_5.setText(_translate("MainWindow", "Z", None))
        self.label_71.setText(_translate("MainWindow", "L", None))
        self.label_68.setText(_translate("MainWindow", "R", None))
        self.label_4.setText(_translate("MainWindow", "Calf", None))
        self.calfADCProgress.setFormat(_translate("MainWindow", "%v", None))
        self.tabs.setTabText(self.tabs.indexOf(self.legTab), _translate("MainWindow", "Leg", None))
        self.label_29.setText(_translate("MainWindow", "PID", None))
        self.label_30.setText(_translate("MainWindow", "P", None))
        self.label_31.setText(_translate("MainWindow", "I", None))
        self.label_32.setText(_translate("MainWindow", "D", None))
        self.label_73.setText(_translate("MainWindow", "Min", None))
        self.label_72.setText(_translate("MainWindow", "Max", None))
        self.label_25.setText(_translate("MainWindow", "PWM", None))
        self.label_26.setText(_translate("MainWindow", "Extend", None))
        self.label_28.setText(_translate("MainWindow", "Retract", None))
        self.label_27.setText(_translate("MainWindow", "Misc", None))
        self.label_33.setText(_translate("MainWindow", "PID future time", None))
        self.label_34.setText(_translate("MainWindow", "Error Threshold", None))
        self.label_12.setText(_translate("MainWindow", "ADC limits", None))
        self.label_11.setText(_translate("MainWindow", "Min", None))
        self.label_10.setText(_translate("MainWindow", "Max", None))
        self.label_13.setText(_translate("MainWindow", "Dither", None))
        self.label_14.setText(_translate("MainWindow", "Time(us)", None))
        self.label_15.setText(_translate("MainWindow", "Amplitude", None))
        self.pidCommitButton.setText(_translate("MainWindow", "Commit", None))
        self.pidJointCombo.setItemText(0, _translate("MainWindow", "Hip", None))
        self.pidJointCombo.setItemText(1, _translate("MainWindow", "Thigh", None))
        self.pidJointCombo.setItemText(2, _translate("MainWindow", "Knee", None))
        self.tabs.setTabText(self.tabs.indexOf(self.PIDTab), _translate("MainWindow", "PID", None))
        self.tabs.setTabText(self.tabs.indexOf(self.bodyTab), _translate("MainWindow", "Body", None))
        self.estopLabel.setText(_translate("MainWindow", "Estop: ?", None))
        self.heightLabel.setText(_translate("MainWindow", "Height: ?", None))
        self.pressureLabel.setText(_translate("MainWindow", "PSI: ?", None))
        self.rpmLabel.setText(_translate("MainWindow", "RPM: ?", None))
        self.oilTempLabel.setText(_translate("MainWindow", "Temp: ?", None))
        self.legsMenu.setTitle(_translate("MainWindow", "Legs", None))
        self.modesMenu.setTitle(_translate("MainWindow", "Modes", None))
        self.calibrationMenu.setTitle(_translate("MainWindow", "Calibration", None))
        self.configurationMenu.setTitle(_translate("MainWindow", "Configuration", None))

from stompy.ui.nogl import LineChart, LegDisplay, BodyDisplay

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

